name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@master
  
    - name: Run custom command
      uses: cedrickring/golang-action@1.4.1
      with:
        args: make build

    - name: Archive Linux provider
      uses: actions/upload-artifact@v1
      with:
        name: terraform-provider-intersight
        path: .build/linux_amd64/terraform-provider-intersight

    - name: Archive Windows provider
      uses: actions/upload-artifact@v1
      with:
        name: terraform-provider-intersight.exe
        path: .build/windows/terraform-provider-intersight.exe

    - name: Archive MacOS provider
      uses: actions/upload-artifact@v1
      with:
        name: terraform-provider-intersight-darwin
        path: .build/darwin/terraform-provider-intersight
